### ISSUE TITLE
Menu on Android

### ISSUE THREAD

**Issue by ricky-sb** [Citizenship-Portal/Frontend-Development#2]
The menu doesn't seem to work on Android in Chrome. When I click it, I don't get the popout.

**Comment by ricky-sb** [comment]
This is an issue with PurgeCSS

**Comment by kayyali18** [comment]
How did you figure that one out?
Never would have thought to look into purgeCSS being the culprit

**Comment by ricky-sb** [comment]
I had a similar problem a few months ago. [See here](https://github.com/ionic-team/ionic/issues/18130#issuecomment-591215562).

**Comment by ricky-sb** [comment]
To go more in-depth, I noticed that it would work on mobile when I ran it in dev mode, but not in production, which made me think it was something with the build script.   

In the production build, I noticed that the classes were being added correctly, but there was no rendering.   

After comparing with the dev build, I realized that the CSS classes didn't exist in the production build (they were getting stripped out), which made me look at purgeCSS.

**Comment by kayyali18** [comment]
"I noticed that it would work on mobile when I ran it in dev mode, but not in production, which made me think it was something with the build script." 
Ok I see
The classes would appear diff between local env and deployed but didn't think the build script was the culprit.
Good to know, thanks!
